version: "3"
services:
  app:
    container_name: app
    image: dockerfile
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
